### PR TITLE
feat: add fonts-inter

### PR DESCRIPTION
**Pull request by xzy-bit**
feat: add fonts-inter

Inter font family.

Log:add fonts-inter
Issues:https://github.com/deepin-community/sig-deepin-sysdev-team/issues/205

### CODE REVIEW

**Comment by chenchongbiao** [comment]
@chenchongbiao

**Comment by chenchongbiao** [comment]
不用新建fonts目录

**Comment by xzy-bit** [comment]
@chenchongbiao  remove

**Comment by UTsweetyfish** [comment]
#2

**Pull request closed without merging**
